### ISSUE TITLE
Request: simplify

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#283] opened 2017-02-17 11:16 UTC
https://github.com/CalebFenton/simplify

**Comment by xorond** [comment] 2017-02-17 20:13
You've done way too many requests for us to handle. Try making pull requests with PKGBUILDs instead. I'll be closing some of your issues.

**Closed by xorond** 2017-02-17 20:13 UTC
Labels: wontfix

**Comment by vdun** [comment] 2017-02-18 23:22
Issues/Requests are meant to draw attention to the Community that this is needed. Others could see this and contribute by make PKGBUILD (personally, I have no big skills making them).
Please reopen them as sooner or later someone else will make the same request.
Having many is a good indication that ArchStrike is growing and getting popular!

**Comment by archey** [comment] 2017-02-18 23:25
This is true, the problem is they stay open for an eternity cause no one ever adds them or packages them. The ones we closed specifically because they will be difficult to pkg and will be quite messy. Most of the ones that we can easily add we have worked on and added, however most of the pkgs you have requested will never work well in Arch mainly because they are out of date in someway or dependent on something that we cant pull in.
